# Generated by Django 6.0.6 on 2026-07-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_listing_body_type_listing_drive_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listingmedia',
            table='panel_listing_media',
        ),
        migrations.AlterModelTable(
            name='savedlisting',
            table='panel_saved_listing',
        ),
    ]
